// <auto-generated />
using System;
using CasoEstudio1_G1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CasoEstudio1_G1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasoEstudio1_G1.Models.Boleto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("VehiculoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("VehiculoId");

                    b.ToTable("Boletos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UsuarioId = 3,
                            VehiculoId = 1
                        },
                        new
                        {
                            Id = 2,
                            UsuarioId = 4,
                            VehiculoId = 2
                        });
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Bueno"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Regular"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Necesita mantenimiento"
                        });
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Hora")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.ToTable("Horarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hora = new TimeSpan(0, 8, 0, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Hora = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Hora = new TimeSpan(0, 18, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.HorarioRuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HorarioId")
                        .HasColumnType("int");

                    b.Property<int>("RutaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HorarioId");

                    b.HasIndex("RutaId");

                    b.ToTable("HorariosRutas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HorarioId = 1,
                            RutaId = 1
                        },
                        new
                        {
                            Id = 2,
                            HorarioId = 2,
                            RutaId = 2
                        });
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.Parada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paradas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Parada 1"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Parada 2"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Parada 3"
                        });
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.ParadaRuta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ParadaId")
                        .HasColumnType("int");

                    b.Property<int>("RutaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParadaId");

                    b.HasIndex("RutaId");

                    b.ToTable("ParadasRutas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ParadaId = 1,
                            RutaId = 1
                        },
                        new
                        {
                            Id = 2,
                            ParadaId = 2,
                            RutaId = 1
                        },
                        new
                        {
                            Id = 3,
                            ParadaId = 3,
                            RutaId = 2
                        });
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Conductor"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Usuario"
                        });
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.Ruta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreRuta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Rutas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Ruta principal",
                            Estado = true,
                            FechaRegistro = new DateTime(2025, 2, 25, 21, 33, 58, 207, DateTimeKind.Local).AddTicks(5166),
                            NombreRuta = "Ruta 1",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Ruta secundaria",
                            Estado = true,
                            FechaRegistro = new DateTime(2025, 2, 25, 21, 33, 58, 207, DateTimeKind.Local).AddTicks(5177),
                            NombreRuta = "Ruta 2",
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contrasenna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Contrasenna = "12345678",
                            Correo = "fabian@gmail.com",
                            NombreCompleto = "Fabian Mata",
                            NombreUsuario = "fabi",
                            RolId = 1,
                            Telefono = "684634524"
                        },
                        new
                        {
                            Id = 2,
                            Contrasenna = "12345678",
                            Correo = "rodolfo@gmail.com",
                            NombreCompleto = "Rodolfo Cruz",
                            NombreUsuario = "rodo",
                            RolId = 1,
                            Telefono = "96939564"
                        },
                        new
                        {
                            Id = 3,
                            Contrasenna = "12345678",
                            Correo = "maria@gmail.com",
                            NombreCompleto = "Maria Canales",
                            NombreUsuario = "mari",
                            RolId = 2,
                            Telefono = "35784925"
                        },
                        new
                        {
                            Id = 4,
                            Contrasenna = "12345678",
                            Correo = "cristopher@gmail.com",
                            NombreCompleto = "Cristopher Nuñez",
                            NombreUsuario = "cris",
                            RolId = 3,
                            Telefono = "684634524"
                        });
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadPasajeros")
                        .HasColumnType("int");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("RutaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("RutaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Vehiculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacidadPasajeros = 50,
                            EstadoId = 1,
                            FechaRegistro = new DateTime(2025, 2, 25, 21, 33, 58, 207, DateTimeKind.Local).AddTicks(5219),
                            Modelo = "Modelo X",
                            Placa = "ABC123",
                            RutaId = 1,
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            CapacidadPasajeros = 40,
                            EstadoId = 2,
                            FechaRegistro = new DateTime(2025, 2, 25, 21, 33, 58, 207, DateTimeKind.Local).AddTicks(5222),
                            Modelo = "Modelo Y",
                            Placa = "DEF456",
                            RutaId = 2,
                            UsuarioId = 2
                        });
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.Boleto", b =>
                {
                    b.HasOne("CasoEstudio1_G1.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasoEstudio1_G1.Models.Vehiculo", "Vehiculo")
                        .WithMany()
                        .HasForeignKey("VehiculoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("Vehiculo");
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.HorarioRuta", b =>
                {
                    b.HasOne("CasoEstudio1_G1.Models.Horario", "Horario")
                        .WithMany()
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasoEstudio1_G1.Models.Ruta", "Ruta")
                        .WithMany()
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Horario");

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.ParadaRuta", b =>
                {
                    b.HasOne("CasoEstudio1_G1.Models.Parada", "Parada")
                        .WithMany()
                        .HasForeignKey("ParadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasoEstudio1_G1.Models.Ruta", "Ruta")
                        .WithMany()
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parada");

                    b.Navigation("Ruta");
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.Ruta", b =>
                {
                    b.HasOne("CasoEstudio1_G1.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.Usuario", b =>
                {
                    b.HasOne("CasoEstudio1_G1.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.Vehiculo", b =>
                {
                    b.HasOne("CasoEstudio1_G1.Models.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasoEstudio1_G1.Models.Ruta", "Ruta")
                        .WithMany()
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CasoEstudio1_G1.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Ruta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CasoEstudio1_G1.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
